# Generated by Django 3.1.7 on 2021-03-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=30)),
                ('place', models.IntegerField()),
                ('date', models.CharField(max_length=30)),
            ],
        ),
    ]
