# Generated by Django 3.1.7 on 2021-03-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=30)),
                ('place', models.IntegerField()),
                ('date', models.DateField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trp_badge', models.BooleanField()),
                ('date', models.DateField()),
                ('age_group', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('points', models.IntegerField()),
            ],
        ),
    ]
