# Generated by Django 3.1.7 on 2021-03-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_table1_table2_table3_table4_table5'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table1',
            new_name='GlobalEvent',
        ),
        migrations.RenameModel(
            old_name='Table3',
            new_name='NationalPart',
        ),
        migrations.RenameModel(
            old_name='Table4',
            new_name='NotNationalPart',
        ),
        migrations.RenameModel(
            old_name='Table5',
            new_name='Online',
        ),
        migrations.RenameModel(
            old_name='Table2',
            new_name='TRPBadge',
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
