# Generated by Django 3.1.7 on 2021-04-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210421_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalevent',
            name='requestID',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='nationalpart',
            name='requestID',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='notnationalpart',
            name='requestID',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='online',
            name='requestID',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='trpbadge',
            name='requestID',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='globalevent',
            name='userID',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='nationalpart',
            name='userID',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='notnationalpart',
            name='userID',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='online',
            name='userID',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='trpbadge',
            name='userID',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
