# Generated by Django 3.1.7 on 2021-05-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210422_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalevent',
            name='userID',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
