# Generated by Django 3.1.7 on 2021-05-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210507_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalevent',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalevent',
            name='userID',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
